version: '3.8'

services:
  backend:
    build: ../yuraproject/
    restart: on-failure
    volumes:
      - static_value:/app/static/
    env_file:
      - ./.env
    command: >
      sh -c "python3 manage.py migrate --no-input &&
             python3 manage.py collectstatic --no-input &&
             gunicorn yuraproject.wsgi:application --bind 0:8000"

  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  static_value:
