# Generated by Django 4.1.1 on 2022-09-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='адрес')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='рейтинг')),
                ('reviews_amount', models.PositiveSmallIntegerField(verbose_name='количество оценок')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('161', 'Кафе'), ('159', 'Бары'), ('192', 'Кинотеатры'), ('373', 'Круглосуточные магазины'), ('193', 'Музеи'), ('168', 'Парки'), ('164', 'Рестораны'), ('611', 'Торговые центры')], max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата запроса')),
            ],
            options={
                'verbose_name': 'запрос',
                'verbose_name_plural': 'запросы',
                'ordering': ('-date',),
            },
        ),
    ]
