# Generated by Django 4.1.1 on 2022-09-24 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='place',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.userrequest', verbose_name='запрос'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['-date'], name='places_user_date_7724f7_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-id'], name='places_plac_id_962135_idx'),
        ),
    ]
